/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Driver
(
    input in,
    input sel,
    output out
);
    assign out = (sel == 1'b1)? in : 1'bz;
endmodule

module \74245_ap_ver  (
  input OE,
  input A1,
  input A2,
  input A3,
  input A4,
  input A5,
  input A6,
  input A7,
  input A8,
  input VCC,
  input GND,
  output B1,
  output B2,
  output B3,
  output B4,
  output B5,
  output B6,
  output B7,
  output B8
);
  Driver Driver_i0 (
    .in( A1 ),
    .sel( OE ),
    .out( B1 )
  );
  Driver Driver_i1 (
    .in( A2 ),
    .sel( OE ),
    .out( B2 )
  );
  Driver Driver_i2 (
    .in( A3 ),
    .sel( OE ),
    .out( B3 )
  );
  Driver Driver_i3 (
    .in( A4 ),
    .sel( OE ),
    .out( B4 )
  );
  Driver Driver_i4 (
    .in( A5 ),
    .sel( OE ),
    .out( B5 )
  );
  Driver Driver_i5 (
    .in( A6 ),
    .sel( OE ),
    .out( B6 )
  );
  Driver Driver_i6 (
    .in( A7 ),
    .sel( OE ),
    .out( B7 )
  );
  Driver Driver_i7 (
    .in( A8 ),
    .sel( OE ),
    .out( B8 )
  );
endmodule
