/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_D_FF_1bit
#(
    parameter Default = 0
)
(
   input D,
   input C,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


// Octal D Flip-Flop with enable
module \74377  (
  input D0,
  input VCC,
  input GND,
  input D1,
  input D2,
  input D3,
  input \~E ,
  input D4,
  input D5,
  input D6,
  input D7,
  input CLK,
  output Q0,
  output Q1,
  output Q2,
  output Q3,
  output Q4,
  output Q5,
  output Q6,
  output Q7
);
  wire s0;
  wire s1;
  wire Q0_temp;
  wire s2;
  wire Q1_temp;
  wire s3;
  wire Q2_temp;
  wire s4;
  wire Q3_temp;
  wire s5;
  wire Q4_temp;
  wire s6;
  wire Q5_temp;
  wire s7;
  wire Q6_temp;
  wire s8;
  wire Q7_temp;
  assign s1 = ~ \~E ;
  assign s0 = ((Q0_temp & \~E ) | (D0 & s1));
  assign s2 = ((Q1_temp & \~E ) | (D1 & s1));
  assign s3 = ((Q2_temp & \~E ) | (D2 & s1));
  assign s4 = ((Q3_temp & \~E ) | (D3 & s1));
  assign s5 = ((Q4_temp & \~E ) | (D4 & s1));
  assign s6 = ((Q5_temp & \~E ) | (D5 & s1));
  assign s7 = ((Q6_temp & \~E ) | (D6 & s1));
  assign s8 = ((Q7_temp & \~E ) | (D7 & s1));
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i0 (
    .D( s0 ),
    .C( CLK ),
    .Q( Q0_temp )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i1 (
    .D( s2 ),
    .C( CLK ),
    .Q( Q1_temp )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i2 (
    .D( s3 ),
    .C( CLK ),
    .Q( Q2_temp )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i3 (
    .D( s4 ),
    .C( CLK ),
    .Q( Q3_temp )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i4 (
    .D( s5 ),
    .C( CLK ),
    .Q( Q4_temp )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i5 (
    .D( s6 ),
    .C( CLK ),
    .Q( Q5_temp )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i6 (
    .D( s7 ),
    .C( CLK ),
    .Q( Q6_temp )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i7 (
    .D( s8 ),
    .C( CLK ),
    .Q( Q7_temp )
  );
  assign Q0 = Q0_temp;
  assign Q1 = Q1_temp;
  assign Q2 = Q2_temp;
  assign Q3 = Q3_temp;
  assign Q4 = Q4_temp;
  assign Q5 = Q5_temp;
  assign Q6 = Q6_temp;
  assign Q7 = Q7_temp;
endmodule

module Driver
(
    input in,
    input sel,
    output out
);
    assign out = (sel == 1'b1)? in : 1'bz;
endmodule

module \74245_ap_ver  (
  input OE,
  input A1,
  input A2,
  input A3,
  input A4,
  input A5,
  input A6,
  input A7,
  input A8,
  input VCC,
  input GND,
  output B1,
  output B2,
  output B3,
  output B4,
  output B5,
  output B6,
  output B7,
  output B8
);
  Driver Driver_i0 (
    .in( A1 ),
    .sel( OE ),
    .out( B1 )
  );
  Driver Driver_i1 (
    .in( A2 ),
    .sel( OE ),
    .out( B2 )
  );
  Driver Driver_i2 (
    .in( A3 ),
    .sel( OE ),
    .out( B3 )
  );
  Driver Driver_i3 (
    .in( A4 ),
    .sel( OE ),
    .out( B4 )
  );
  Driver Driver_i4 (
    .in( A5 ),
    .sel( OE ),
    .out( B5 )
  );
  Driver Driver_i5 (
    .in( A6 ),
    .sel( OE ),
    .out( B6 )
  );
  Driver Driver_i6 (
    .in( A7 ),
    .sel( OE ),
    .out( B7 )
  );
  Driver Driver_i7 (
    .in( A8 ),
    .sel( OE ),
    .out( B8 )
  );
endmodule

module \74377_8_bit_register  (
  input d7,
  input d6,
  input d5,
  input d4,
  input d3,
  input d2,
  input d1,
  input d0,
  input \!Load ,
  input Enable,
  input Clock,
  output bus0,
  output bus1,
  output bus2,
  output bus3,
  output bus4,
  output bus5,
  output bus6,
  output bus7
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  \74377  \74377_i0 (
    .\~E ( \!Load  ),
    .D0( d0 ),
    .D1( d1 ),
    .D2( d2 ),
    .D3( d3 ),
    .GND( 1'b0 ),
    .CLK( Clock ),
    .D4( d4 ),
    .D5( d5 ),
    .D6( d6 ),
    .D7( d7 ),
    .VCC( 1'b1 ),
    .Q0( s0 ),
    .Q1( s1 ),
    .Q2( s2 ),
    .Q3( s3 ),
    .Q4( s4 ),
    .Q5( s5 ),
    .Q6( s6 ),
    .Q7( s7 )
  );
  \74245_ap_ver  \74245_ap_ver_i1 (
    .OE( Enable ),
    .A1( s0 ),
    .A2( s1 ),
    .A3( s2 ),
    .A4( s3 ),
    .A5( s4 ),
    .A6( s5 ),
    .A7( s6 ),
    .A8( s7 ),
    .GND( 1'b0 ),
    .VCC( 1'b1 ),
    .B1( bus0 ),
    .B2( bus1 ),
    .B3( bus2 ),
    .B4( bus3 ),
    .B5( bus4 ),
    .B6( bus5 ),
    .B7( bus6 ),
    .B8( bus7 )
  );
endmodule
