/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module DIG_D_FF_AS_1bit
#(
    parameter Default = 0
)
(
   input Set,
   input D,
   input C,
   input Clr,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q  = ~state;

    always @ (posedge C or posedge Clr or posedge Set)
    begin
        if (Set)
            state <= 1'b1;
        else if (Clr)
            state <= 'h0;
        else
            state <= D;
    end

    initial begin
        state = Default;
    end
endmodule

// octal D-type flip-flop with clear
module \74273  (
  input CP,
  input \~MR ,
  input D0,
  input D1,
  input D2,
  input D3,
  input D4,
  input D5,
  input D6,
  input D7,
  input VCC,
  input GND,
  output Q0,
  output Q1,
  output Q2,
  output Q3,
  output Q4,
  output Q5,
  output Q6,
  output Q7
);
  wire s0;
  assign s0 = ~ \~MR ;
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i0 (
    .Set( 1'b0 ),
    .D( D1 ),
    .C( CP ),
    .Clr( s0 ),
    .Q( Q1 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i1 (
    .Set( 1'b0 ),
    .D( D2 ),
    .C( CP ),
    .Clr( s0 ),
    .Q( Q2 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i2 (
    .Set( 1'b0 ),
    .D( D3 ),
    .C( CP ),
    .Clr( s0 ),
    .Q( Q3 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i3 (
    .Set( 1'b0 ),
    .D( D0 ),
    .C( CP ),
    .Clr( s0 ),
    .Q( Q0 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i4 (
    .Set( 1'b0 ),
    .D( D4 ),
    .C( CP ),
    .Clr( s0 ),
    .Q( Q4 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i5 (
    .Set( 1'b0 ),
    .D( D5 ),
    .C( CP ),
    .Clr( s0 ),
    .Q( Q5 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i6 (
    .Set( 1'b0 ),
    .D( D6 ),
    .C( CP ),
    .Clr( s0 ),
    .Q( Q6 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i7 (
    .Set( 1'b0 ),
    .D( D7 ),
    .C( CP ),
    .Clr( s0 ),
    .Q( Q7 )
  );
endmodule

module Driver
(
    input in,
    input sel,
    output out
);
    assign out = (sel == 1'b1)? in : 1'bz;
endmodule

module \74245_ap_ver  (
  input OE,
  input A1,
  input A2,
  input A3,
  input A4,
  input A5,
  input A6,
  input A7,
  input A8,
  input VCC,
  input GND,
  output B1,
  output B2,
  output B3,
  output B4,
  output B5,
  output B6,
  output B7,
  output B8
);
  Driver Driver_i0 (
    .in( A1 ),
    .sel( OE ),
    .out( B1 )
  );
  Driver Driver_i1 (
    .in( A2 ),
    .sel( OE ),
    .out( B2 )
  );
  Driver Driver_i2 (
    .in( A3 ),
    .sel( OE ),
    .out( B3 )
  );
  Driver Driver_i3 (
    .in( A4 ),
    .sel( OE ),
    .out( B4 )
  );
  Driver Driver_i4 (
    .in( A5 ),
    .sel( OE ),
    .out( B5 )
  );
  Driver Driver_i5 (
    .in( A6 ),
    .sel( OE ),
    .out( B6 )
  );
  Driver Driver_i6 (
    .in( A7 ),
    .sel( OE ),
    .out( B7 )
  );
  Driver Driver_i7 (
    .in( A8 ),
    .sel( OE ),
    .out( B8 )
  );
endmodule

module \74273_8_bit_register  (
  input d7,
  input d6,
  input d5,
  input d4,
  input d3,
  input d2,
  input d1,
  input d0,
  input \!Load ,
  input Clock,
  input Enable,
  output bus0,
  output bus1,
  output bus2,
  output bus3,
  output bus4,
  output bus5,
  output bus6,
  output bus7
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  assign s4 = (~ \!Load  & Clock);
  \74273  \74273_i0 (
    .\~MR ( 1'b1 ),
    .D0( d0 ),
    .D1( d1 ),
    .D2( d2 ),
    .D3( d3 ),
    .GND( 1'b0 ),
    .CP( s4 ),
    .D4( d4 ),
    .D5( d5 ),
    .D6( d6 ),
    .D7( d7 ),
    .VCC( 1'b1 ),
    .Q0( s0 ),
    .Q1( s1 ),
    .Q2( s2 ),
    .Q3( s3 ),
    .Q4( s5 ),
    .Q5( s6 ),
    .Q6( s7 ),
    .Q7( s8 )
  );
  \74245_ap_ver  \74245_ap_ver_i1 (
    .OE( Enable ),
    .A1( s0 ),
    .A2( s1 ),
    .A3( s2 ),
    .A4( s3 ),
    .A5( s5 ),
    .A6( s6 ),
    .A7( s7 ),
    .A8( s8 ),
    .GND( 1'b0 ),
    .VCC( 1'b1 ),
    .B1( bus0 ),
    .B2( bus1 ),
    .B3( bus2 ),
    .B4( bus3 ),
    .B5( bus4 ),
    .B6( bus5 ),
    .B7( bus6 ),
    .B8( bus7 )
  );
endmodule
